### ISSUE TITLE
wrong class for Visual bell in documentation

### ISSUE THREAD

**Issue by GDreyV** [thomas-lowry/figma-plugin-ds#12]
in that section https://thomas-lowry.github.io/figma-plugin-ds/#visual-bell
Loading has wrapper `<div class="visual-bell">`
which must be `<div class="visual-bell visual-bell--loading">` instead.

**Comment by thomas-lowry** [comment]
Thanks for flagging. Are you using this anywhere? I was looking to deprecate this component because there is now a msging system in Figma. If you have a good use case and are using it, I can keep it as part of the package.

**Comment by GDreyV** [comment]
Sorry, I didn't get, what do you mean "msging system"? I'm using the component to show progress status.

**Comment by thomas-lowry** [comment]
When I first created this, and added this component, there was no ability to push a toast to Figma.
`figma.notify('toast message here');`

But Figma has added that since. There is no loading state or warning state option currently provided by Figma, but it reduces the need for this. If you are still using this I will keep it.

Thanks!
